### ISSUE TITLE
Still a troublesome Linux issues raw_file.instrument_methods_count

### ISSUE THREAD

**Issue by keesh-elucid** [ethz-institute-of-microbiology/fisher_py#15]
Hello,
Under Linux Centos 7, we are still being plagued by this error,
Can you please test version 18 on a Mac or Linux box?

 `ERROR: test_get_instrument_methods_count_cross_platform (MprcExtractRaw2_per_spectrum_tests.TestMprcExtractRaw2)
This should be tested on Windows 10, 11, MacOS, and CentosOS 7,8
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/odin/dev/scripts/deployments/MprcExtractRaw/MprcExtractRaw2/src/test/MprcExtractRaw2_per_spectrum_tests.py", line 233, in test_get_instrument_methods_count_cross_platform
    instrument_methods_count = raw_file.instrument_methods_count
  File "/apps/software/biotools/python/3.9.9/lib/python3.9/site-packages/fisher_py/raw_file_reader/raw_file_access.py", line 119, in instrument_methods_count
    return self._get_wrapped_object_().InstrumentMethodsCount
System.NullReferenceException: Object reference not set to an instance of an object
  at ThermoFisher.CommonCore.RawFileReader.DeviceStorage.GetStorageNames (ThermoFisher.CommonCore.RawFileReader.IOleStorage storage, ThermoFisher.CommonCore.RawFileReader.StgType storageType) [0x00000] in <614d17bf8c0447909a4884c93b4318b5>:0
  at ThermoFisher.CommonCore.RawFileReader.DeviceStorage.EnumSubStgsNoRecursion (System.Collections.Generic.List`1[T] storageDescriptions) [0x00000] in <614d17bf8c0447909a4884c93b4318b5>:0
  at ThermoFisher.CommonCore.RawFileReader.StructWrappers.Method.GetMethodData (ThermoFisher.CommonCore.RawFileReader.Facade.Interfaces.IMemMapReader viewer, System.Int64 startPos, System.Collections.Generic.List`1[T] storageDesc) [0x00027] in <614d17bf8c0447909a4884c93b4318b5>:0
  at ThermoFisher.CommonCore.RawFileReader.StructWrappers.Method+<>c__DisplayClass25_0.<Load>b__1 () [0x00000] in <614d17bf8c0447909a4884c93b4318b5>:0
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <ed178240b0494cd89a00d276a4c37080>:0
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <ed178240b0494cd89a00d276a4c37080>:0
  at System.Lazy`1[T].CreateValue () [0x00074] in <ed178240b0494cd89a00d276a4c37080>:0
  at System.Lazy`1[T].get_Value () [0x0000a] in <ed178240b0494cd89a00d276a4c37080>:0
  at ThermoFisher.CommonCore.RawFileReader.StructWrappers.Method.get_StorageDescriptions () [0x00008] in <614d17bf8c0447909a4884c93b4318b5>:0
  at ThermoFisher.CommonCore.RawFileReader.RawFileAccessBase.get_InstrumentMethodsCount () [0x0003b] in <614d17bf8c0447909a4884c93b4318b5>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <ed178240b0494cd89a00d276a4c37080>:0`

**Comment by keesh-elucid** [comment]
We are wondering if there has been any progress on "Still a troublesome Linux issues raw_file.instrument_methods_count" ?
thx 
kischell.eric@mayo.edu

**Comment by dowerner** [comment]
Dear @keesh-elucid 

Sorry for the very late reply. Github still does not forward notifications to me. It seems to me that the problems you are experiencing are related to the raw file you are trying to access. I was unable to reproduce those issues with the raw files I use for testing.
If you send me a similar raw file without critical data I may be able to debug the issue in detail. As an alternative I can implement a fallback that just ignores the instrument_methods_count that cannot be read from your files.

Let me know how you want to proceed,

Cheers Dominik

**Comment by dpsmca** [comment]
Hi @dowerner,

In the `fisher_py` fork I created for our project, I created a `bug/instrument_methods_count` branch and created a `test_data` directory inside the `examples` directory -- it should be accessible [here](https://github.com/dpsmca/fisher_py/tree/bug/instrument_methods_count/examples/test_data). It contains two small raw files. Both of those files cause the InstrumentMethodsCount crash when I run `raw_file_reader_example.py` on them, using Mac or Linux.

**Comment by dowerner** [comment]
Finally, I had the chance to test your files using a Linux system (WSL - Ubuntu 20.04 on Windows 10). It turns out that the problem occurs for all .raw files on Linux but not on Windows. Sadly, the issue is situated within the .NET binaries (provided to us by ThermoFisher) and not within the Python code. What I can offer is to implement a fallback that just returns "None" if the count cannot be extracted, obviously this won't do you much good if you need this parameter. Hopefully, we can replace the DLLs in the future so it works properly on all platforms.

**Comment by dowerner** [comment]
The fix is now implemented in version 19, feel free to open a new issue if anythin else pops up (meanwhile I fixed the github notification issue on my side 👍 )

**Comment by keesh0** [comment]
So does your fix address the following?
So, I created a C# only version of my small method.
It ran fine on Linux.
rawFile.InstrumentMethodsCount  // OK
rawFile.GetInstrumentMethod(i)  // OK
But, the Python wrapper crashed.

**Comment by dowerner** [comment]
To be honest I did not run a C# example. I assumed pythonnet would invoke the offending properties and methods similar to the .NET runtime in C#. If you have an idea how to fix this I'll gladly have a look. As it stands I don't know how to fix it in fisher_py.

**Comment by keesh0** [comment]
Sure, let me check with my colleague.
thx e.-
